---
- hosts: all
  sudo: yes
  tasks:
    - name: install httpd
      yum: pkg=httpd state=latest
      notify:
        - restart httpd
    - name: modify docroot
      lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^DocumentRoot \"/var/www/html\"" line="DocumentRoot \"/web\"" state=present
      notify:
        - restart httpd
    - name: modify directory
      lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^<Directory \"/var/www/html\">" line="<Directory \"/web\">" state=present
      notify:
        - restart httpd
    - name: create file
      file: path=/web/index.php state=touch
    - stat: path=/web/index.php
      register: file_path
    - copy: content="192.168.33.20" dest="/web/index.php"
      when: file_path.stat.exists == true

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
